### ISSUE TITLE
Termo de responsabilidade

### ISSUE THREAD

**Issue by DantasB** [CorchoForce/pav-front#42]
Pelo fato de estarmos pedindo o CPF do usuário, é necessário adicionarmos um termo de responsabilidade quanto ao uso desse documento.

**Comment by DantasB** [comment]
https://www.tributa.net/modelo-termo-de-consentimento-para-tratamento-de-dados-pessoais-lei-geral-de-protecao-de-dados-pessoais-lgpd

**Comment by TalesCoutinho** [comment]
Mas aí a gente precisaria de um CNPJ, né? Como faz?

**Comment by DantasB** [comment]
@TalesCoutinho deixa isso on-hold. Qualquer coisa a gente só retira o CPF. Vou dar uma consultada com o meu conhecido pra ver isso de CNPJ
